# Generated by Django 6.0.2 on 2026-02-12 09:29

import django.core.validators
import django.db.models.deletion
import videos.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
            ],
            options={
                'verbose_name': 'Kategorie',
                'verbose_name_plural': 'Kategorien',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titel')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='Slug')),
                ('description', models.TextField(verbose_name='Beschreibung')),
                ('original_video', models.FileField(help_text='Original hochgeladene Video-Datei', upload_to=videos.models.video_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'avi', 'mov', 'mkv'])], verbose_name='Original Video')),
                ('video_360p', models.FileField(blank=True, null=True, upload_to=videos.models.video_upload_path, verbose_name='360p Version')),
                ('video_480p', models.FileField(blank=True, null=True, upload_to=videos.models.video_upload_path, verbose_name='480p Version')),
                ('video_720p', models.FileField(blank=True, null=True, upload_to=videos.models.video_upload_path, verbose_name='720p Version')),
                ('video_1080p', models.FileField(blank=True, null=True, upload_to=videos.models.video_upload_path, verbose_name='1080p Version')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=videos.models.thumbnail_upload_path, verbose_name='Thumbnail')),
                ('duration', models.IntegerField(default=0, help_text='Dauer des Videos in Sekunden', verbose_name='Dauer (Sekunden)')),
                ('quality', models.CharField(choices=[('SD', 'Standard Definition (480p)'), ('HD', 'High Definition (720p)'), ('FHD', 'Full HD (1080p)'), ('4K', '4K Ultra HD')], default='HD', max_length=3, verbose_name='Qualität')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='Dateigröße (Bytes)')),
                ('status', models.CharField(choices=[('draft', 'Entwurf'), ('processing', 'Wird verarbeitet'), ('published', 'Veröffentlicht'), ('archived', 'Archiviert')], default='draft', max_length=20, verbose_name='Status')),
                ('is_featured', models.BooleanField(default=False, help_text='Als Featured Video auf der Startseite anzeigen', verbose_name='Hervorgehoben')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Veröffentlicht am')),
                ('view_count', models.IntegerField(default=0, verbose_name='Anzahl Aufrufe')),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)], verbose_name='Bewertung')),
                ('director', models.CharField(blank=True, max_length=200, verbose_name='Regisseur')),
                ('cast', models.TextField(blank=True, help_text='Komma-getrennte Liste', verbose_name='Besetzung')),
                ('release_year', models.IntegerField(blank=True, null=True, verbose_name='Erscheinungsjahr')),
                ('language', models.CharField(default='Deutsch', max_length=50, verbose_name='Sprache')),
                ('age_rating', models.CharField(choices=[('0', 'FSK 0'), ('6', 'FSK 6'), ('12', 'FSK 12'), ('16', 'FSK 16'), ('18', 'FSK 18')], default='0', max_length=10, verbose_name='Altersfreigabe')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('categories', models.ManyToManyField(related_name='videos', to='videos.category', verbose_name='Kategorien')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_videos', to=settings.AUTH_USER_MODEL, verbose_name='Hochgeladen von')),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VideoComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Inhalt')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('is_edited', models.BooleanField(default=False, verbose_name='Bearbeitet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_comments', to=settings.AUTH_USER_MODEL, verbose_name='Benutzer')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='videos.video', verbose_name='Video')),
            ],
            options={
                'verbose_name': 'Kommentar',
                'verbose_name_plural': 'Kommentare',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VideoRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(help_text='Bewertung von 1 bis 5 Sternen', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Bewertung')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_ratings', to=settings.AUTH_USER_MODEL, verbose_name='Benutzer')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='videos.video', verbose_name='Video')),
            ],
            options={
                'verbose_name': 'Bewertung',
                'verbose_name_plural': 'Bewertungen',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['-created_at'], name='videos_vide_created_1f1e45_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['status'], name='videos_vide_status_107761_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['is_featured'], name='videos_vide_is_feat_70e3c9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='videorating',
            unique_together={('video', 'user')},
        ),
    ]
