# Generated by Django 6.0.2 on 2026-02-17 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LegalPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_type', models.CharField(choices=[('privacy', 'Privacy Policy'), ('imprint', 'Imprint'), ('terms', 'Terms of Service')], help_text='Type of legal page', max_length=20, unique=True)),
                ('title', models.CharField(help_text='Page title', max_length=200)),
                ('content', models.TextField(help_text='Page content in HTML format')),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='Last update timestamp')),
                ('is_published', models.BooleanField(default=True, help_text='Whether the page is published')),
            ],
            options={
                'verbose_name': 'Legal Page',
                'verbose_name_plural': 'Legal Pages',
                'ordering': ['page_type'],
            },
        ),
    ]
